"""users table

Revision ID: 31553e8604cb
Revises: 
Create Date: 2018-04-28 13:18:40.390921

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '31553e8604cb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=64), nullable=True),
    sa.Column('location', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_location'), 'user', ['location'], unique=True)
    op.create_index(op.f('ix_user_name'), 'user', ['name'], unique=False)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.drop_index('username', table_name='users')
    op.drop_table('users')
    op.drop_table('user_skills')
    op.drop_index('skill', table_name='skills')
    op.drop_table('skills')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('skills',
    sa.Column('skill_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('skill', mysql.VARCHAR(length=256), nullable=False),
    sa.PrimaryKeyConstraint('skill_id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_index('skill', 'skills', ['skill'], unique=True)
    op.create_table('user_skills',
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('skill_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.skill_id'], name='users_skills_unique_skill'),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name='users_skills_unique_user'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_table('users',
    sa.Column('user_id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('name', mysql.VARCHAR(length=256), nullable=False),
    sa.Column('location', mysql.VARCHAR(length=256), nullable=False),
    sa.Column('pass', mysql.VARCHAR(length=256), nullable=False),
    sa.Column('username', mysql.VARCHAR(length=256), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_index('username', 'users', ['username'], unique=True)
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_name'), table_name='user')
    op.drop_index(op.f('ix_user_location'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
